# Generated by Django 3.2.7 on 2021-10-11 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fanta_soccer_app', '0016_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=22)),
                ('number_of_squads', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(4)])),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanta_soccer_app.squad')),
            ],
        ),
    ]
