# Generated by Django 3.2.7 on 2021-10-13 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0016_profile'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='squad',
        ),
        migrations.AddField(
            model_name='league',
            name='squad_list',
            field=models.ManyToManyField(to='fanta_soccer_app.Squad'),
        ),
        migrations.AlterField(
            model_name='league',
            name='number_of_squads',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(4)]),
        ),
    ]
