# Generated by Django 3.2.7 on 2021-10-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0016_profile'),
        ('tournament', '0002_auto_20211013_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='squad_list',
        ),
        migrations.AddField(
            model_name='league',
            name='squads',
            field=models.ManyToManyField(blank=True, to='fanta_soccer_app.Squad'),
        ),
    ]
