# Generated by Django 3.2.7 on 2021-10-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20211013_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
