# Generated by Django 3.2.4 on 2021-06-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='t_name',
            new_name='team_name',
        ),
    ]
