# Generated by Django 3.2.4 on 2021-06-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0003_auto_20210616_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='positions',
            field=models.CharField(choices=[('1', 'GK'), ('2', 'DC'), ('3', 'DL'), ('4', 'MF'), ('5', 'WF'), ('6', 'SS'), ('7', 'CF')], default='', max_length=2),
        ),
    ]
