# Generated by Django 3.2.4 on 2021-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0004_positions_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='positions',
            field=models.CharField(choices=[(1, 'GK'), (2, 'DC'), (3, 'DL'), (4, 'MF'), (5, 'WF'), (6, 'SS'), (7, 'CF')], default=1, max_length=2),
        ),
    ]
