# Generated by Django 3.2.4 on 2021-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0005_alter_positions_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerslist_file', models.CharField(max_length=20)),
            ],
        ),
    ]
