# Generated by Django 3.2.4 on 2021-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0006_playersavailable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayersAvailable',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=25),
        ),
    ]
