# Generated by Django 3.2.4 on 2021-07-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0008_remove_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fanta_soccer_app.team'),
            preserve_default=False,
        ),
    ]
