# Generated by Django 3.2.4 on 2021-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0009_auto_20210714_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=25)),
                ('team_real', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=5)),
            ],
        ),
    ]
