# Generated by Django 3.2.4 on 2021-07-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0010_available_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Available_player',
            new_name='AvailablePlayer',
        ),
    ]
