# Generated by Django 3.2.4 on 2021-07-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0012_auto_20210720_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableplayer',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fanta_soccer_app.squad'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
