# Generated by Django 3.2.4 on 2021-08-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0013_auto_20210722_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableplayer',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanta_soccer_app.squad'),
        ),
    ]
