# Generated by Django 3.2.7 on 2021-10-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableplayer',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fanta_soccer_app.squad'),
        ),
    ]
