# Generated by Django 3.2.7 on 2021-10-17 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0017_alter_availableplayer_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=22)),
                ('number_of_squads', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(4)])),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='tournament_in',
            field=models.ManyToManyField(to='fanta_soccer_app.League'),
        ),
    ]
