# Generated by Django 3.2.7 on 2021-10-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0019_auto_20211026_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='type',
        ),
    ]
