# Generated by Django 3.2.7 on 2021-10-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0021_league_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='type',
            new_name='type_of_tournament',
        ),
    ]
