# Generated by Django 3.2.7 on 2021-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0023_alter_league_type_of_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='squads',
            field=models.ManyToManyField(related_name='leagues', to='fanta_soccer_app.Squad'),
        ),
    ]
