# Generated by Django 3.2.7 on 2021-11-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0024_alter_league_squads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
