# Generated by Django 3.2.7 on 2021-11-01 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanta_soccer_app', '0025_delete_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=22)),
                ('number_of_squads', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(4)])),
                ('type_of_tournament', models.CharField(blank=True, choices=[('RR', 'Round Robin'), ('EL', 'Elimination')], max_length=25, null=True)),
                ('squads', models.ManyToManyField(related_name='leagues', to='fanta_soccer_app.Squad')),
            ],
        ),
    ]
